# Generated by Django 4.2.2 on 2023-06-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=100, verbose_name='Price')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100, null=True, verbose_name='Sale Price')),
            ],
        ),
    ]
