# Generated by Django 4.2.2 on 2023-06-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_myproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='myproduct',
            name='product',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
