# Generated by Django 4.2.2 on 2023-06-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_myproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproduct',
            name='product',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
