# Generated by Django 4.2.2 on 2023-06-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_myproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproduct',
            name='product',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
    ]
